#!/usr/bin/env bash
#
# Configures the natively installed PostgreSQL on the db droplet.
#
# doploy uploads and runs this on every deploy, so every step has to be safe to
# repeat. The parts that change between deploys are the addresses: DB_LISTEN_IP
# and ALLOWED_CLIENT_IP are set from droplet private addresses in doploy.yml and
# rewritten each time, which is what lets the API connect after the web droplet
# is rebuilt with a new address.
#
# Every value below comes from the setup env file doploy writes (mode 0600) and
# sources before this runs. This script is uploaded verbatim -- doploy does not
# interpolate script contents -- so the substitution happens in doploy.yml.

set -euo pipefail

: "${APP_DB_NAME:?APP_DB_NAME is required}"
: "${APP_DB_USER:?APP_DB_USER is required}"
: "${APP_DB_PASSWORD:?APP_DB_PASSWORD is required}"
: "${DB_LISTEN_IP:?DB_LISTEN_IP is required}"
: "${ALLOWED_CLIENT_IP:?ALLOWED_CLIENT_IP is required}"
: "${PGDATA_MOUNT:?PGDATA_MOUNT is required}"

PG_VERSION="$(ls -1 /etc/postgresql | sort -V | tail -1)"
CONF_DIR="/etc/postgresql/${PG_VERSION}/main"
CONF="${CONF_DIR}/postgresql.conf"
HBA="${CONF_DIR}/pg_hba.conf"
DATA_DIR="${PGDATA_MOUNT}/${PG_VERSION}/main"

echo "postgres ${PG_VERSION}, config in ${CONF_DIR}"

# --- move the cluster onto the block volume, once -------------------------
#
# The volume survives the droplet being destroyed and rebuilt; the boot disk
# does not. Only copy when the target is empty, so a redeploy never clobbers
# live data.

# PG_VERSION rather than the directory itself is the completeness marker: every
# valid cluster has it, so its absence means the directory is empty or a
# previous copy was interrupted. Testing the directory alone would silently skip
# the move and then start Postgres on a half-copied cluster.
if [ ! -f "${DATA_DIR}/PG_VERSION" ]; then
  echo "moving the data directory to ${DATA_DIR}"

  systemctl stop postgresql "postgresql@${PG_VERSION}-main" >/dev/null 2>&1 || true

  # systemctl returns once the unit is stopping, not once it has stopped. The
  # postmaster can still be shutting down, and transient files such as
  # postmaster.pid disappear underneath the copy if it starts too early.
  for _ in $(seq 1 60); do
    if ! pgrep -u postgres -f 'bin/postgres' >/dev/null 2>&1; then
      break
    fi
    sleep 1
  done

  if pgrep -u postgres -f 'bin/postgres' >/dev/null 2>&1; then
    echo "postgres is still running after 60s; refusing to copy a live cluster" >&2
    exit 1
  fi

  # Safe because we only get here when PG_VERSION is absent, so there is no
  # complete cluster at this path to destroy.
  rm -rf "${DATA_DIR}"
  mkdir -p "${DATA_DIR}"

  cp -a "/var/lib/postgresql/${PG_VERSION}/main/." "${DATA_DIR}/"
  rm -f "${DATA_DIR}/postmaster.pid"

  chown -R postgres:postgres "${PGDATA_MOUNT}"
  chmod 700 "${DATA_DIR}"
else
  echo "data directory already on the volume, leaving it alone"
fi

# --- listen on loopback and the private interface only ---------------------
#
# Never the public one. This is what keeps Postgres unreachable from the
# internet regardless of firewall configuration.

set_conf() {
  local key="$1" value="$2"
  if grep -Eq "^[#[:space:]]*${key}[[:space:]]*=" "${CONF}"; then
    sed -i -E "s|^[#[:space:]]*${key}[[:space:]]*=.*|${key} = ${value}|" "${CONF}"
  else
    printf '%s = %s\n' "${key}" "${value}" >>"${CONF}"
  fi
}

set_conf data_directory "'${DATA_DIR}'"
set_conf listen_addresses "'localhost,${DB_LISTEN_IP}'"
set_conf password_encryption "'scram-sha-256'"

# --- host-based auth: allow exactly the web droplet ------------------------
#
# Rewritten every deploy. The managed block is delimited so it can be replaced
# without disturbing anything else in the file.

BEGIN_MARK="# BEGIN doploy-managed"
END_MARK="# END doploy-managed"

# Drop any previous block, then append the current one.
sed -i "/^${BEGIN_MARK}$/,/^${END_MARK}$/d" "${HBA}"

{
  echo "${BEGIN_MARK}"
  echo "# Regenerated by doploy on each deploy. Edits here are lost."
  echo "host    ${APP_DB_NAME}    ${APP_DB_USER}    ${ALLOWED_CLIENT_IP}/32    scram-sha-256"
  echo "${END_MARK}"
} >>"${HBA}"

echo "pg_hba allows ${APP_DB_USER}@${ALLOWED_CLIENT_IP}/32"

# --- start and wait --------------------------------------------------------

systemctl enable postgresql >/dev/null 2>&1 || true
systemctl restart postgresql

for _ in $(seq 1 30); do
  if pg_isready -q -h /var/run/postgresql; then
    break
  fi
  sleep 1
done

if ! pg_isready -q -h /var/run/postgresql; then
  echo "postgres did not become ready; recent log:" >&2
  journalctl -u postgresql --no-pager -n 40 >&2 || true
  exit 1
fi

# --- role and database ------------------------------------------------------

run_sql() {
  sudo -u postgres psql -v ON_ERROR_STOP=1 -q --no-psqlrc "$@"
}

# The password goes through a mode-600 temporary file rather than the command
# line, so it never appears in the droplet's process list. Single quotes inside
# it are doubled, which is how SQL escapes them.
ESCAPED_PASSWORD="${APP_DB_PASSWORD//\'/\'\'}"

umask 077
TMP_SQL="$(mktemp)"
trap 'rm -f "${TMP_SQL}"' EXIT

if run_sql -tAc "SELECT 1 FROM pg_roles WHERE rolname = '${APP_DB_USER}'" | grep -q 1; then
  ROLE_ACTION="ALTER"
else
  ROLE_ACTION="CREATE"
fi

printf "%s ROLE %s WITH LOGIN PASSWORD '%s';\n" \
  "${ROLE_ACTION}" "${APP_DB_USER}" "${ESCAPED_PASSWORD}" >"${TMP_SQL}"
chown postgres "${TMP_SQL}"

run_sql -f "${TMP_SQL}"
rm -f "${TMP_SQL}"

echo "role ${APP_DB_USER} is present (${ROLE_ACTION})"

if ! run_sql -tAc "SELECT 1 FROM pg_database WHERE datname = '${APP_DB_NAME}'" | grep -q 1; then
  echo "creating database ${APP_DB_NAME}"
  run_sql -c "CREATE DATABASE ${APP_DB_NAME} OWNER ${APP_DB_USER}"
else
  echo "database ${APP_DB_NAME} already exists"
fi

# --- schema -----------------------------------------------------------------
#
# init.sql is written to be idempotent (CREATE TABLE IF NOT EXISTS), so it runs
# on every deploy and applies anything newly added.

echo "applying /opt/microblog/init.sql"
sudo -u postgres psql -v ON_ERROR_STOP=1 -q -d "${APP_DB_NAME}" -f /opt/microblog/init.sql

run_sql -d "${APP_DB_NAME}" -c "GRANT ALL ON SCHEMA public TO ${APP_DB_USER}"
run_sql -d "${APP_DB_NAME}" -c "GRANT ALL ON ALL TABLES IN SCHEMA public TO ${APP_DB_USER}"
run_sql -d "${APP_DB_NAME}" -c "GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO ${APP_DB_USER}"

echo "postgres setup complete"
