package spec

import (
	"fmt"
	"path"
	"strings"

	"gopkg.in/yaml.v3"
)

// buildDirName is the subdirectory of the project's remote directory that holds
// uploaded build contexts, one per service.
const buildDirName = "build"

// composeFile is the document doploy writes to each droplet. Field order here
// controls the order in the generated YAML.
type composeFile struct {
	Services map[string]*composeService `yaml:"services"`
	Volumes  map[string]*emptyMapping   `yaml:"volumes,omitempty"`
}

// emptyMapping renders as `{}`, which is how compose declares a default-driver
// named volume.
type emptyMapping struct{}

func (e *emptyMapping) MarshalYAML() (any, error) { return map[string]any{}, nil }

type composeService struct {
	Image         string            `yaml:"image,omitempty"`
	Build         *composeBuild     `yaml:"build,omitempty"`
	ContainerName string            `yaml:"container_name,omitempty"`
	Restart       string            `yaml:"restart,omitempty"`
	Entrypoint    []string          `yaml:"entrypoint,omitempty"`
	Command       []string          `yaml:"command,omitempty"`
	Ports         []string          `yaml:"ports,omitempty"`
	Expose        []string          `yaml:"expose,omitempty"`
	Environment   map[string]string `yaml:"environment,omitempty"`
	EnvFile       []string          `yaml:"env_file,omitempty"`
	Volumes       []string          `yaml:"volumes,omitempty"`
	DependsOn     []string          `yaml:"depends_on,omitempty"`
	Labels        map[string]string `yaml:"labels,omitempty"`
	User          string            `yaml:"user,omitempty"`
	WorkingDir    string            `yaml:"working_dir,omitempty"`
	Privileged    bool              `yaml:"privileged,omitempty"`
	Healthcheck   *composeHealth    `yaml:"healthcheck,omitempty"`
	Deploy        *Deploy           `yaml:"deploy,omitempty"`
}

// composeBuild points at the context doploy uploaded, relative to the compose
// file, so the generated document works if someone runs compose by hand.
type composeBuild struct {
	Context    string            `yaml:"context"`
	Dockerfile string            `yaml:"dockerfile,omitempty"`
	Args       map[string]string `yaml:"args,omitempty"`
}

type composeHealth struct {
	Test        []string `yaml:"test,omitempty"`
	Interval    string   `yaml:"interval,omitempty"`
	Timeout     string   `yaml:"timeout,omitempty"`
	Retries     int      `yaml:"retries,omitempty"`
	StartPeriod string   `yaml:"start_period,omitempty"`
}

// ComposeFile renders the docker compose document for one droplet, covering
// exactly the services scheduled onto it.
//
// A droplet with no services returns nil, nil. That is a legitimate shape now
// that setup blocks exist: a database host runs no containers at all.
func (s *Spec) ComposeFile(droplet string) ([]byte, error) {
	services := s.ServicesOn(droplet)
	if len(services) == 0 {
		return nil, nil
	}

	file := &composeFile{
		Services: make(map[string]*composeService, len(services)),
		Volumes:  map[string]*emptyMapping{},
	}

	for _, svc := range services {
		cs := &composeService{
			Image:       svc.Image,
			Restart:     svc.Restart,
			Entrypoint:  svc.Entrypoint,
			Command:     svc.Command,
			Ports:       svc.Ports,
			Expose:      svc.Expose,
			Environment: svc.Env,
			EnvFile:     svc.EnvFile,
			Volumes:     svc.Volumes,
			DependsOn:   svc.DependsOn,
			Labels:      withDoployLabels(svc.Labels, s.Project, svc.Name),
			User:        svc.User,
			WorkingDir:  svc.WorkingDir,
			Privileged:  svc.Privileged,
			Deploy:      svc.Deploy,
		}
		if b := svc.Build; b != nil {
			cs.Build = &composeBuild{
				Context:    "./" + path.Join(buildDirName, svc.Name),
				Dockerfile: b.Dockerfile,
				Args:       b.Args,
			}
		}
		if hc := svc.Healthcheck; hc != nil {
			cs.Healthcheck = &composeHealth{
				Test:        hc.Test,
				Interval:    hc.Interval,
				Timeout:     hc.Timeout,
				Retries:     hc.Retries,
				StartPeriod: hc.StartPeriod,
			}
		}
		file.Services[svc.Name] = cs

		// Any mount whose source is not a host path is a docker named volume
		// and has to be declared at the top level.
		for _, mount := range svc.Volumes {
			if source, _, found := strings.Cut(mount, ":"); found && isNamedVolume(source) {
				file.Volumes[source] = &emptyMapping{}
			}
		}
	}

	if len(file.Volumes) == 0 {
		file.Volumes = nil
	}

	body, err := yaml.Marshal(file)
	if err != nil {
		return nil, fmt.Errorf("rendering compose file: %w", err)
	}

	header := fmt.Sprintf("# Generated by doploy from %s -- do not edit.\n# project: %s, droplet: %s\n",
		s.Path, s.Project, droplet)
	return append([]byte(header), body...), nil
}

// isNamedVolume distinguishes a docker volume name from a host bind path.
func isNamedVolume(source string) bool {
	return !strings.HasPrefix(source, "/") &&
		!strings.HasPrefix(source, "./") &&
		!strings.HasPrefix(source, "../") &&
		!strings.HasPrefix(source, "~")
}

// withDoployLabels stamps ownership labels onto every container so operators
// can tell what doploy manages when they SSH in themselves.
func withDoployLabels(existing map[string]string, project, service string) map[string]string {
	labels := make(map[string]string, len(existing)+2)
	for k, v := range existing {
		labels[k] = v
	}
	labels["doploy.project"] = project
	labels["doploy.service"] = service
	return labels
}

// ComposeProjectName is the compose project name used on the remote host. It
// scopes container names and networks to this doploy project.
func (s *Spec) ComposeProjectName() string { return s.Project }

// RemoteDir is the directory on each droplet holding the generated compose file
// and environment file.
func (s *Spec) RemoteDir() string { return "/opt/doploy/" + s.Project }

// RemoteBuildDir is where a service's uploaded build context lands. It matches
// the relative path written into the compose file.
func (s *Spec) RemoteBuildDir(service string) string {
	return path.Join(s.RemoteDir(), buildDirName, service)
}
