package spec

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"
)

func TestComposeFileIncludesOnlyThatDropletsServices(t *testing.T) {
	s, err := Load(writeSpec(t, `
project: demo
defaults:
  region: nyc3
  size: s-1vcpu-1gb
  image: docker-20-04
droplets:
  web:
    default: true
  worker: {}
services:
  api:
    image: ghcr.io/example/api:1.0
    ports: ["80:8080"]
  redis:
    image: redis:7-alpine
  cruncher:
    droplet: worker
    image: ghcr.io/example/cruncher:1.0
`))
	if err != nil {
		t.Fatal(err)
	}

	out, err := s.ComposeFile("web")
	if err != nil {
		t.Fatal(err)
	}

	var parsed struct {
		Services map[string]map[string]any `yaml:"services"`
	}
	if err := yaml.Unmarshal(out, &parsed); err != nil {
		t.Fatalf("generated compose file is not valid YAML: %v\n%s", err, out)
	}

	if len(parsed.Services) != 2 {
		t.Fatalf("expected 2 services on web, got %d: %v", len(parsed.Services), parsed.Services)
	}
	for _, want := range []string{"api", "redis"} {
		if _, ok := parsed.Services[want]; !ok {
			t.Errorf("missing service %q", want)
		}
	}
	if _, leaked := parsed.Services["cruncher"]; leaked {
		t.Error("cruncher belongs to worker and must not appear in web's compose file")
	}
}

func TestComposeFileDeclaresNamedVolumes(t *testing.T) {
	s, err := Load(writeSpec(t, `
project: demo
defaults:
  region: nyc3
  size: s-1vcpu-1gb
  image: docker-20-04
droplets:
  web:
    volumes:
      - name: blocks
        size_gb: 10
services:
  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /mnt/blocks/backups:/backups
`))
	if err != nil {
		t.Fatal(err)
	}

	out, err := s.ComposeFile("web")
	if err != nil {
		t.Fatal(err)
	}

	var parsed struct {
		Volumes map[string]any `yaml:"volumes"`
	}
	if err := yaml.Unmarshal(out, &parsed); err != nil {
		t.Fatal(err)
	}

	if _, ok := parsed.Volumes["pgdata"]; !ok {
		t.Errorf("named volume pgdata should be declared, got %v", parsed.Volumes)
	}
	// A host bind mount is not a docker named volume and must not be declared.
	if _, wrong := parsed.Volumes["/mnt/blocks/backups"]; wrong {
		t.Error("a bind mount path was declared as a named volume")
	}
}

func TestComposeFileStampsOwnershipLabels(t *testing.T) {
	s, err := Load(writeSpec(t, `
project: demo
defaults:
  region: nyc3
  size: s-1vcpu-1gb
  image: docker-20-04
services:
  api:
    image: nginx
    labels:
      team: platform
`))
	if err != nil {
		t.Fatal(err)
	}

	out, err := s.ComposeFile("default")
	if err != nil {
		t.Fatal(err)
	}

	var parsed struct {
		Services map[string]struct {
			Labels map[string]string `yaml:"labels"`
		} `yaml:"services"`
	}
	if err := yaml.Unmarshal(out, &parsed); err != nil {
		t.Fatal(err)
	}

	labels := parsed.Services["api"].Labels
	if labels["doploy.project"] != "demo" || labels["doploy.service"] != "api" {
		t.Errorf("ownership labels missing: %v", labels)
	}
	if labels["team"] != "platform" {
		t.Errorf("user label was dropped: %v", labels)
	}
}

func TestComposeFileIsDeterministic(t *testing.T) {
	content := `
project: demo
defaults:
  region: nyc3
  size: s-1vcpu-1gb
  image: docker-20-04
services:
  zebra:
    image: nginx
  alpha:
    image: nginx
  middle:
    image: nginx
`
	s, err := Load(writeSpec(t, content))
	if err != nil {
		t.Fatal(err)
	}

	first, err := s.ComposeFile("default")
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 5; i++ {
		again, err := s.ComposeFile("default")
		if err != nil {
			t.Fatal(err)
		}
		if string(again) != string(first) {
			t.Fatal("compose output changed between runs; it must be stable so redeploys do not churn")
		}
	}
}

func TestComposeFileIsNilForServicelessDroplet(t *testing.T) {
	// A droplet with only a setup block -- a native database host -- runs no
	// containers, so it gets no compose file rather than an error.
	s, err := Load(writeSpec(t, `
project: demo
defaults:
  region: nyc3
  size: s-1vcpu-1gb
  image: ubuntu-24-04-x64
droplets:
  web:
    default: true
  db:
    setup:
      packages: [postgresql]
services:
  api:
    image: nginx
`))
	if err != nil {
		t.Fatal(err)
	}

	content, err := s.ComposeFile("db")
	if err != nil {
		t.Fatalf("a serviceless droplet is legitimate, got error: %v", err)
	}
	if content != nil {
		t.Errorf("expected no compose file for db, got:\n%s", content)
	}

	if s.HasServices("db") {
		t.Error("db should report no services")
	}
	if !s.HasServices("web") {
		t.Error("web should report services")
	}
}

func TestComposeFileHasProvenanceHeader(t *testing.T) {
	s, err := Load(writeSpec(t, `
project: demo
defaults:
  region: nyc3
  size: s-1vcpu-1gb
  image: docker-20-04
services:
  api:
    image: nginx
`))
	if err != nil {
		t.Fatal(err)
	}

	out, err := s.ComposeFile("default")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(out), "# Generated by doploy") {
		t.Errorf("expected a provenance header so nobody hand-edits the file, got:\n%s", out)
	}
}

func TestRemoteDirIsNamespacedByProject(t *testing.T) {
	s := &Spec{Project: "demo"}
	if got := s.RemoteDir(); got != "/opt/doploy/demo" {
		t.Errorf("RemoteDir() = %q, want /opt/doploy/demo", got)
	}
}
