package deploy

import (
	"fmt"
	"os"
	"path"
	"strings"

	"github.com/jeremyaboyd/doploy/internal/archive"
	"github.com/jeremyaboyd/doploy/internal/provision"
	"github.com/jeremyaboyd/doploy/internal/spec"
	"github.com/jeremyaboyd/doploy/internal/sshx"
	"github.com/jeremyaboyd/doploy/internal/ui"
)

// remoteSetupDir holds uploaded setup scripts on the droplet.
const remoteSetupDir = "/opt/doploy/setup"

// runSetup applies a droplet's host-level setup: packages, files, then
// commands, in that order.
//
// Setup runs on every deploy, not just the first. That is a deliberate choice
// -- it means a changed init script actually takes effect -- but it puts the
// burden of idempotency on the scripts themselves.
func (d *Deployer) runSetup(client *sshx.Client, state *provision.DropletState, out *logWriter) error {
	setup := state.Spec.Setup
	if setup == nil {
		return nil
	}

	if len(setup.Packages) > 0 {
		ui.Substep("installing %s", strings.Join(setup.Packages, ", "))
		if err := client.Stream(aptInstallScript(setup.Packages), out); err != nil {
			return fmt.Errorf("installing packages: %w", err)
		}
	}

	envFile, err := d.writeSetupEnv(client, state.Name, setup)
	if err != nil {
		return err
	}

	for _, file := range setup.Files {
		if err := d.uploadSetupFile(client, file); err != nil {
			return err
		}
	}

	for i, command := range setup.Run {
		if err := d.runSetupCommand(client, out, state.Name, i, command, envFile); err != nil {
			return err
		}
	}
	return nil
}

// writeSetupEnv writes the setup environment to a 0600 file and returns its
// path, or "" when the droplet declares no setup env.
func (d *Deployer) writeSetupEnv(client *sshx.Client, droplet string, setup *spec.Setup) (string, error) {
	if len(setup.Env) == 0 {
		return "", nil
	}

	var b strings.Builder
	b.WriteString("# Generated by doploy. Sourced before each setup command.\n")
	for _, key := range sortedKeys(setup.Env) {
		// Single quotes keep the value literal; embedded quotes are escaped.
		fmt.Fprintf(&b, "%s='%s'\n", key, strings.ReplaceAll(setup.Env[key], "'", `'\''`))
	}

	remote := path.Join(remoteSetupDir, d.Spec.Project+"-"+droplet+".env")
	ui.Substep("writing setup environment (%d values) to %s", len(setup.Env), remote)

	if err := client.WriteFile(remote, []byte(b.String()), "0600"); err != nil {
		return "", err
	}
	return remote, nil
}

// withSetupEnv prefixes a command so it runs with the setup environment loaded.
func withSetupEnv(envFile, command string) string {
	if envFile == "" {
		return "set -eu\n" + command
	}
	return strings.Join([]string{
		"set -eu",
		"set -a",
		". " + shellQuote(envFile),
		"set +a",
		command,
	}, "\n")
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	for i := 1; i < len(keys); i++ {
		for j := i; j > 0 && keys[j] < keys[j-1]; j-- {
			keys[j], keys[j-1] = keys[j-1], keys[j]
		}
	}
	return keys
}

// uploadSetupFile copies one file to the droplet, interpolating it first when
// the spec marks it as a template.
func (d *Deployer) uploadSetupFile(client *sshx.Client, file *spec.SetupFile) error {
	local := d.Spec.LocalPath(file.Source)

	content, err := os.ReadFile(local)
	if err != nil {
		return fmt.Errorf("reading setup file %s: %w", file.Source, err)
	}

	if file.Template {
		resolved, err := d.vars.ResolveString(string(content))
		if err != nil {
			return fmt.Errorf("setup file %s: %w", file.Source, err)
		}
		content = []byte(resolved)
	}

	mode := file.Mode
	if mode == "" {
		mode = "0644"
	}

	ui.Substep("uploading %s -> %s", file.Source, file.Dest)
	return client.WriteFile(file.Dest, content, mode)
}

// runSetupCommand executes one setup entry.
//
// An entry that names a script file on disk is uploaded and run, so setup logic
// can live in a real .sh file with syntax highlighting and its own history
// rather than being crammed into YAML. Anything else runs inline.
func (d *Deployer) runSetupCommand(client *sshx.Client, out *logWriter, droplet string, index int, command, envFile string) error {
	if local, ok := d.resolveScript(command); ok {
		content, err := os.ReadFile(local)
		if err != nil {
			return fmt.Errorf("reading setup script %s: %w", command, err)
		}

		resolved, err := d.vars.ResolveString(string(content))
		if err != nil {
			return fmt.Errorf("setup script %s: %w", command, err)
		}

		remote := path.Join(remoteSetupDir, fmt.Sprintf("%02d-%s", index, path.Base(toSlash(command))))
		ui.Substep("running %s", command)

		if err := client.WriteFile(remote, []byte(resolved), "0700"); err != nil {
			return err
		}
		if err := client.Stream(withSetupEnv(envFile, "bash "+shellQuote(remote)), out); err != nil {
			return fmt.Errorf("setup script %s failed on %s: %w", command, droplet, err)
		}
		return nil
	}

	// Inline commands are not echoed. They are interpolated spec values, so
	// they can legitimately contain secrets, and this output routinely ends up
	// in CI logs.
	ui.Substep("running setup command %d of %d", index+1, d.setupCommandCount(droplet))
	if err := client.Stream(withSetupEnv(envFile, command), out); err != nil {
		return fmt.Errorf("setup command %d failed on %s: %w", index+1, droplet, err)
	}
	return nil
}

func (d *Deployer) setupCommandCount(droplet string) int {
	if spec := d.Spec.Droplets[droplet]; spec != nil && spec.Setup != nil {
		return len(spec.Setup.Run)
	}
	return 0
}

// resolveScript reports whether a run entry names a shell script on disk.
func (d *Deployer) resolveScript(command string) (string, bool) {
	// A command with a newline or shell metacharacters is plainly inline, and
	// must not be probed as a filename.
	if strings.ContainsAny(command, "\n|&;<>$(){}") {
		return "", false
	}
	if !strings.HasSuffix(strings.TrimSpace(command), ".sh") {
		return "", false
	}

	local := d.Spec.LocalPath(strings.TrimSpace(command))
	info, err := os.Stat(local)
	if err != nil || info.IsDir() {
		return "", false
	}
	return local, true
}

// aptInstallScript installs packages non-interactively.
//
// apt-get update is retried because cloud-init often still holds the dpkg lock
// on a freshly created droplet.
func aptInstallScript(packages []string) string {
	quoted := make([]string, len(packages))
	for i, pkg := range packages {
		quoted[i] = shellQuote(pkg)
	}

	return fmt.Sprintf(`
set -eu
export DEBIAN_FRONTEND=noninteractive

for attempt in 1 2 3 4 5 6; do
  if apt-get update -qq; then
    break
  fi
  echo "apt-get update failed (attempt $attempt), another process may hold the lock; retrying"
  sleep 10
done

apt-get install -y -qq --no-install-recommends %s
`, strings.Join(quoted, " "))
}

// packContext builds the upload archive for a build context.
func packContext(dir string) ([]byte, error) {
	return archive.TarGz(dir)
}

func toSlash(p string) string { return strings.ReplaceAll(p, "\\", "/") }
